version: '3'
services:
#Service sa toma el Dockerfile de ./laboratorio
 host1:
  build: ./laboratorio
  hostname: host1
  cap_add:
  - ALL
  networks:
   red3:
 host2:
  build: ./laboratorio
  hostname: host2
  cap_add:
  - ALL
  networks:
   red3:
 host3:
  build: ./laboratorio
  hostname: host3
  cap_add:
  - ALL
  networks:
   red5:
 host4:
  build: ./laboratorio
  hostname: host4
  cap_add:
  - ALL
  networks:
   red5:
 enc35:
  build: ./laboratorio
  hostname: enc35
  cap_add:
  - ALL
  sysctls:
    net.ipv4.ip_forward: 1
  networks:
   red3:
   red5:
networks:
  red3:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.3.0/24
  red5:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.5.0/24
