version: '3'
services:
#Service sa toma el Dockerfile de ./laboratorio
 host1:
  build: ./laboratorio
  hostname: host1
  cap_add:
  - ALL
  networks:
   net1:
 host2:
  build: ./laboratorio
  hostname: host2
  cap_add:
  - ALL
  networks:
   net1:
 host3:
  build: ./laboratorio
  hostname: host3
  cap_add:
  - ALL
  networks:
   net2:
 gt1:
  build: ./laboratorio
  hostname: gt1
  cap_add:
  - ALL
  sysctls:
    net.ipv4.ip_forward: 1
  networks:
   net1:
   net2:
networks:
  net1:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.2.0/24
  net2:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.3.0/24

